<a href="https://colab.research.google.com/github/Esteban-Prince/VDA-CPE-031-CPE21S4/blob/main/Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 3

**Load Files Into a DataFrame**

In [ ]:
import pandas as pd
df = pd.read_csv('Grade.csv')
print(df)

    CpE 0323-1  Quiz 1  Python Fundamentals  Conditional Statements  \
0         Name      50                  100                     100
1    STUDENT 1      33                  100                     100
2    STUDENT 2      22                  100                     100
3    STUDENT 3      42                  100                     100
4    STUDENT 4      34                  100                     100
5    STUDENT 5      38                  100                     100
6    STUDENT 6      30                  100                     100
7    STUDENT 7      24                  100                     100
8    STUDENT 8      37                  100                     100
9    STUDENT 9       0                  100                     100
10  STUDENT 10      43                  100                     100
11  STUDENT 11      35                  100                     100
12  STUDENT 12      41                  100                     100
13  STUDENT 13      37                  100                     100
14  STUDENT 14       0                  100                     100
15  STUDENT 15      37                  100                     100
16  STUDENT 16      31                  100                     100
17  STUDENT 17      28                  100                     100
18  STUDENT 18      43                  100                     100
19  STUDENT 19      35                  100                     100
20  STUDENT 20      31                  100                     100
21  STUDENT 20      31                  100                     100
22  STUDENT 22      35                  100                     100
23  STUDENT 23      31                  100                     100
24  STUDENT 24       0                  100                     100
25  STUDENT 25      31                  100                     100
26  STUDENT 26       0                  100                     100
27  STUDENT 27      40                  100                     100
28  STUDENT 28      40                  100                     100
29  STUDENT 29      36                  100                     100

    Loop Statement  Data Structure  Image Acquisition  Lab 1  Lab 2  Lab 3  \
0              100             100                100    100    100    100
1              100             100                100     90     90     90
2              100             100                100     80     75     75
3              100             100                100     90     80     90
4              100             100                100     80     75     75
5              100             100                100     90     80     90
6              100             100                100     80     75     75
7              100             100                100     90     80     90
8              100             100                100     90     80     90
9              100             100                100     90     90     90
10             100             100                100     95     95     95
11             100             100                100     90     90     90
12             100             100                100     90     90     90
13             100             100                100     90     90     90
14              75             100                100     95     95     95
15             100              75                 75     90     80     90
16             100             100                100     90     80     90
17             100             100                100     90     80     90
18             100             100                100     90     80     90
19             100             100                100     90     90     90
20             100             100                100     90     90     90
21             100             100                100     90     90     90
22             100             100                100     90     90     90
23             100             100                100     80     75     75
24              75              75                 75     90     80     90
25             100             100                100     95     95     95
26              75              75                 75     90     80     90
27             100             100                100     80     75     75
28             100             100                100     90     90     90
29             100             100                100     90     90     90

    Lab 4  Lab 5
0     100    100
1      90     90
2      75     95
3      90     90
4      75     95
5      90     90
6      75     95
7      90     90
8      90     95
9      90     90
10     95     80
11     90     90
12     90     90
13     90     90
14     95     80
15     90     90
16     90     90
17     90     95
18     90     95
19     90     90
20     90     90
21     90     90
22     90     90
23     75     95
24     90     95
25     95     80
26     90     95
27     75     95
28     90     90
29     90     90

**File upload**

In [ ]:
from google.colab import files
uploaded = files.upload()

**Viewing the Data (Head and Tail)**

In [ ]:
import pandas as pd
df = pd.read_csv('Grade.csv')
print(df)
print(df.head(10))
print(df.tail(10))

    CpE 0323-1  Quiz 1  Python Fundamentals  Conditional Statements  \
0         Name      50                  100                     100
1    STUDENT 1      33                  100                     100
2    STUDENT 2      22                  100                     100
3    STUDENT 3      42                  100                     100
4    STUDENT 4      34                  100                     100
5    STUDENT 5      38                  100                     100
6    STUDENT 6      30                  100                     100
7    STUDENT 7      24                  100                     100
8    STUDENT 8      37                  100                     100
9    STUDENT 9       0                  100                     100
10  STUDENT 10      43                  100                     100
11  STUDENT 11      35                  100                     100
12  STUDENT 12      41                  100                     100
13  STUDENT 13      37                  100                     100
14  STUDENT 14       0                  100                     100
15  STUDENT 15      37                  100                     100
16  STUDENT 16      31                  100                     100
17  STUDENT 17      28                  100                     100
18  STUDENT 18      43                  100                     100
19  STUDENT 19      35                  100                     100
20  STUDENT 20      31                  100                     100
21  STUDENT 20      31                  100                     100
22  STUDENT 22      35                  100                     100
23  STUDENT 23      31                  100                     100
24  STUDENT 24       0                  100                     100
25  STUDENT 25      31                  100                     100
26  STUDENT 26       0                  100                     100
27  STUDENT 27      40                  100                     100
28  STUDENT 28      40                  100                     100
29  STUDENT 29      36                  100                     100

    Loop Statement  Data Structure  Image Acquisition  Lab 1  Lab 2  Lab 3  \
0              100             100                100    100    100    100
1              100             100                100     90     90     90
2              100             100                100     80     75     75
3              100             100                100     90     80     90
4              100             100                100     80     75     75
5              100             100                100     90     80     90
6              100             100                100     80     75     75
7              100             100                100     90     80     90
8              100             100                100     90     80     90
9              100             100                100     90     90     90
10             100             100                100     95     95     95
11             100             100                100     90     90     90
12             100             100                100     90     90     90
13             100             100                100     90     90     90
14              75             100                100     95     95     95
15             100              75                 75     90     80     90
16             100             100                100     90     80     90
17             100             100                100     90     80     90
18             100             100                100     90     80     90
19             100             100                100     90     90     90
20             100             100                100     90     90     90
21             100             100                100     90     90     90
22             100             100                100     90     90     90
23             100             100                100     80     75     75
24              75              75                 75     90     80     90
25             100             100                100     95     95     95
26              75              75                 75     90     80     90
27             100             100                100     80     75     75
28             100             100                100     90     90     90
29             100             100                100     90     90     90

    Lab 4  Lab 5
0     100    100
1      90     90
2      75     95
3      90     90
4      75     95
5      90     90
6      75     95
7      90     90
8      90     95
9      90     90
10     95     80
11     90     90
12     90     90
13     90     90
14     95     80
15     90     90
16     90     90
17     90     95
18     90     95
19     90     90
20     90     90
21     90     90
22     90     90
23     75     95
24     90     95
25     95     80
26     90     95
27     75     95
28     90     90
29     90     90
  CpE 0323-1  Quiz 1  Python Fundamentals  Conditional Statements  \
0       Name      50                  100                     100
1  STUDENT 1      33                  100                     100
2  STUDENT 2      22                  100                     100
3  STUDENT 3      42                  100                     100
4  STUDENT 4      34                  100                     100
5  STUDENT 5      38                  100                     100
6  STUDENT 6      30                  100                     100
7  STUDENT 7      24                  100                     100
8  STUDENT 8      37                  100                     100
9  STUDENT 9       0                  100                     100

   Loop Statement  Data Structure  Image Acquisition  Lab 1  Lab 2  Lab 3  \
0             100             100                100    100    100    100
1             100             100                100     90     90     90
2             100             100                100     80     75     75
3             100             100                100     90     80     90
4             100             100                100     80     75     75
5             100             100                100     90     80     90
6             100             100                100     80     75     75
7             100             100                100     90     80     90
8             100             100                100     90     80     90
9             100             100                100     90     90     90

   Lab 4  Lab 5
0    100    100
1     90     90
2     75     95
3     90     90
4     75     95
5     90     90
6     75     95
7     90     90
8     90     95
9     90     90
    CpE 0323-1  Quiz 1  Python Fundamentals  Conditional Statements  \
20  STUDENT 20      31                  100                     100
21  STUDENT 20      31                  100                     100
22  STUDENT 22      35                  100                     100
23  STUDENT 23      31                  100                     100
24  STUDENT 24       0                  100                     100
25  STUDENT 25      31                  100                     100
26  STUDENT 26       0                  100                     100
27  STUDENT 27      40                  100                     100
28  STUDENT 28      40                  100                     100
29  STUDENT 29      36                  100                     100

    Loop Statement  Data Structure  Image Acquisition  Lab 1  Lab 2  Lab 3  \
20             100             100                100     90     90     90
21             100             100                100     90     90     90
22             100             100                100     90     90     90
23             100             100                100     80     75     75
24              75              75                 75     90     80     90
25             100             100                100     95     95     95
26              75              75                 75     90     80     90
27             100             100                100     80     75     75
28             100             100                100     90     90     90
29             100             100                100     90     90     90

    Lab 4  Lab 5
20     90     90
21     90     90
22     90     90
23     75     95
24     90     95
25     95     80
26     90     95
27     75     95
28     90     90
29     90     90

**Removing Duplicates**

In [ ]:
print(df.duplicated())
df.drop_duplicates(inplace = True)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21     True
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [ ]:
df.drop_duplicates(inplace = True)
print(df)

    CpE 0323-1  Quiz 1  Python Fundamentals  Conditional Statements  \
0         Name      50                  100                     100
1    STUDENT 1      33                  100                     100
2    STUDENT 2      22                  100                     100
3    STUDENT 3      42                  100                     100
4    STUDENT 4      34                  100                     100
5    STUDENT 5      38                  100                     100
6    STUDENT 6      30                  100                     100
7    STUDENT 7      24                  100                     100
8    STUDENT 8      37                  100                     100
9    STUDENT 9       0                  100                     100
10  STUDENT 10      43                  100                     100
11  STUDENT 11      35                  100                     100
12  STUDENT 12      41                  100                     100
13  STUDENT 13      37                  100                     100
14  STUDENT 14       0                  100                     100
15  STUDENT 15      37                  100                     100
16  STUDENT 16      31                  100                     100
17  STUDENT 17      28                  100                     100
18  STUDENT 18      43                  100                     100
19  STUDENT 19      35                  100                     100
20  STUDENT 20      31                  100                     100
22  STUDENT 22      35                  100                     100
23  STUDENT 23      31                  100                     100
24  STUDENT 24       0                  100                     100
25  STUDENT 25      31                  100                     100
26  STUDENT 26       0                  100                     100
27  STUDENT 27      40                  100                     100
28  STUDENT 28      40                  100                     100
29  STUDENT 29      36                  100                     100

    Loop Statement  Data Structure  Image Acquisition  Lab 1  Lab 2  Lab 3  \
0              100             100                100    100    100    100
1              100             100                100     90     90     90
2              100             100                100     80     75     75
3              100             100                100     90     80     90
4              100             100                100     80     75     75
5              100             100                100     90     80     90
6              100             100                100     80     75     75
7              100             100                100     90     80     90
8              100             100                100     90     80     90
9              100             100                100     90     90     90
10             100             100                100     95     95     95
11             100             100                100     90     90     90
12             100             100                100     90     90     90
13             100             100                100     90     90     90
14              75             100                100     95     95     95
15             100              75                 75     90     80     90
16             100             100                100     90     80     90
17             100             100                100     90     80     90
18             100             100                100     90     80     90
19             100             100                100     90     90     90
20             100             100                100     90     90     90
22             100             100                100     90     90     90
23             100             100                100     80     75     75
24              75              75                 75     90     80     90
25             100             100                100     95     95     95
26              75              75                 75     90     80     90
27             100             100                100     80     75     75
28             100             100                100     90     90     90
29             100             100                100     90     90     90

    Lab 4  Lab 5
0     100    100
1      90     90
2      75     95
3      90     90
4      75     95
5      90     90
6      75     95
7      90     90
8      90     95
9      90     90
10     95     80
11     90     90
12     90     90
13     90     90
14     95     80
15     90     90
16     90     90
17     90     95
18     90     95
19     90     90
20     90     90
22     90     90
23     75     95
24     90     95
25     95     80
26     90     95
27     75     95
28     90     90
29     90     90

**Tabulate**

In [ ]:
from tabulate import tabulate
print(tabulate(df, headers='keys', tablefmt='psql', showindex = False))

+--------------+----------+-----------------------+--------------------------+------------------+------------------+---------------------+---------+---------+---------+---------+---------+
| CpE 0323-1   |   Quiz 1 |   Python Fundamentals |   Conditional Statements |   Loop Statement |   Data Structure |   Image Acquisition |   Lab 1 |   Lab 2 |   Lab 3 |   Lab 4 |   Lab 5 |
|--------------+----------+-----------------------+--------------------------+------------------+------------------+---------------------+---------+---------+---------+---------+---------|
| Name         |       50 |                   100 |                      100 |              100 |              100 |                 100 |     100 |     100 |     100 |     100 |     100 |
| STUDENT 1    |       33 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      90 |      90 |      90 |      90 |
| STUDENT 2    |       22 |                   100 |                      100 |              100 |              100 |                 100 |      80 |      75 |      75 |      75 |      95 |
| STUDENT 3    |       42 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      80 |      90 |      90 |      90 |
| STUDENT 4    |       34 |                   100 |                      100 |              100 |              100 |                 100 |      80 |      75 |      75 |      75 |      95 |
| STUDENT 5    |       38 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      80 |      90 |      90 |      90 |
| STUDENT 6    |       30 |                   100 |                      100 |              100 |              100 |                 100 |      80 |      75 |      75 |      75 |      95 |
| STUDENT 7    |       24 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      80 |      90 |      90 |      90 |
| STUDENT 8    |       37 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      80 |      90 |      90 |      95 |
| STUDENT 9    |        0 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      90 |      90 |      90 |      90 |
| STUDENT 10   |       43 |                   100 |                      100 |              100 |              100 |                 100 |      95 |      95 |      95 |      95 |      80 |
| STUDENT 11   |       35 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      90 |      90 |      90 |      90 |
| STUDENT 12   |       41 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      90 |      90 |      90 |      90 |
| STUDENT 13   |       37 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      90 |      90 |      90 |      90 |
| STUDENT 14   |        0 |                   100 |                      100 |               75 |              100 |                 100 |      95 |      95 |      95 |      95 |      80 |
| STUDENT 15   |       37 |                   100 |                      100 |              100 |               75 |                  75 |      90 |      80 |      90 |      90 |      90 |
| STUDENT 16   |       31 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      80 |      90 |      90 |      90 |
| STUDENT 17   |       28 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      80 |      90 |      90 |      95 |
| STUDENT 18   |       43 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      80 |      90 |      90 |      95 |
| STUDENT 19   |       35 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      90 |      90 |      90 |      90 |
| STUDENT 20   |       31 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      90 |      90 |      90 |      90 |
| STUDENT 22   |       35 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      90 |      90 |      90 |      90 |
| STUDENT 23   |       31 |                   100 |                      100 |              100 |              100 |                 100 |      80 |      75 |      75 |      75 |      95 |
| STUDENT 24   |        0 |                   100 |                      100 |               75 |               75 |                  75 |      90 |      80 |      90 |      90 |      95 |
| STUDENT 25   |       31 |                   100 |                      100 |              100 |              100 |                 100 |      95 |      95 |      95 |      95 |      80 |
| STUDENT 26   |        0 |                   100 |                      100 |               75 |               75 |                  75 |      90 |      80 |      90 |      90 |      95 |
| STUDENT 27   |       40 |                   100 |                      100 |              100 |              100 |                 100 |      80 |      75 |      75 |      75 |      95 |
| STUDENT 28   |       40 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      90 |      90 |      90 |      90 |
| STUDENT 29   |       36 |                   100 |                      100 |              100 |              100 |                 100 |      90 |      90 |      90 |      90 |      90 |
+--------------+----------+-----------------------+--------------------------+------------------+------------------+---------------------+---------+---------+---------+---------+---------+

In [ ]:
print(tabulate(df))

--  ----------  --  ---  ---  ---  ---  ---  ---  ---  ---  ---  ---
 0  Name        50  100  100  100  100  100  100  100  100  100  100
 1  STUDENT 1   33  100  100  100  100  100   90   90   90   90   90
 2  STUDENT 2   22  100  100  100  100  100   80   75   75   75   95
 3  STUDENT 3   42  100  100  100  100  100   90   80   90   90   90
 4  STUDENT 4   34  100  100  100  100  100   80   75   75   75   95
 5  STUDENT 5   38  100  100  100  100  100   90   80   90   90   90
 6  STUDENT 6   30  100  100  100  100  100   80   75   75   75   95
 7  STUDENT 7   24  100  100  100  100  100   90   80   90   90   90
 8  STUDENT 8   37  100  100  100  100  100   90   80   90   90   95
 9  STUDENT 9    0  100  100  100  100  100   90   90   90   90   90
10  STUDENT 10  43  100  100  100  100  100   95   95   95   95   80
11  STUDENT 11  35  100  100  100  100  100   90   90   90   90   90
12  STUDENT 12  41  100  100  100  100  100   90   90   90   90   90
13  STUDENT 13  37  100  100  100  100  100   90   90   90   90   90
14  STUDENT 14   0  100  100   75  100  100   95   95   95   95   80
15  STUDENT 15  37  100  100  100   75   75   90   80   90   90   90
16  STUDENT 16  31  100  100  100  100  100   90   80   90   90   90
17  STUDENT 17  28  100  100  100  100  100   90   80   90   90   95
18  STUDENT 18  43  100  100  100  100  100   90   80   90   90   95
19  STUDENT 19  35  100  100  100  100  100   90   90   90   90   90
20  STUDENT 20  31  100  100  100  100  100   90   90   90   90   90
22  STUDENT 22  35  100  100  100  100  100   90   90   90   90   90
23  STUDENT 23  31  100  100  100  100  100   80   75   75   75   95
24  STUDENT 24   0  100  100   75   75   75   90   80   90   90   95
25  STUDENT 25  31  100  100  100  100  100   95   95   95   95   80
26  STUDENT 26   0  100  100   75   75   75   90   80   90   90   95
27  STUDENT 27  40  100  100  100  100  100   80   75   75   75   95
28  STUDENT 28  40  100  100  100  100  100   90   90   90   90   90
29  STUDENT 29  36  100  100  100  100  100   90   90   90   90   90
--  ----------  --  ---  ---  ---  ---  ---  ---  ---  ---  ---  ---

# CHALLENGE

In [ ]:
# Import SampleData.csv to Google Colab
import pandas as pd
#from google.colab import files
#uploaded = files.upload()

# Readthe contents of SampleData.csv
df = pd.read_csv('SampleData.csv')
print("These are the contents of SampleData.csv")
print(tabulate(df, headers='keys', tablefmt='psql', showindex = True))
# Show all top 10 records
print("\n\nThese are the top 10 contents of SampleData.csv")
print(tabulate(df.head(10), headers='keys', tablefmt='psql', showindex = True))

# Show all bottom 10 records
print("\n\nThese are the bottom 10 contents of SampleData.csv")
print(tabulate(df.tail(10), headers='keys', tablefmt='psql', showindex = True))

# Eliminate all duplicated records
print("\n\nThese are the contents of SampleDataNew.csv")
df.drop_duplicates(inplace = True)
print(tabulate(df, headers='keys', tablefmt='psql', showindex = True))

# Save the contents (removed duplicate records) into new file SampleDataNew.csv
df.to_csv('SampleDataNew.csv', index=True)

These are the contents of SampleData.csv
+----+-------------+----------+----------+---------+---------+-------------+----------+
|    | OrderDate   | Region   | Rep      | Item    |   Units |   Unit Cost | Total    |
|----+-------------+----------+----------+---------+---------+-------------+----------|
|  0 | 1/6/21      | East     | Jones    | Pencil  |      95 |        1.99 | 189.05   |
|  1 | 1/23/21     | Central  | Kivell   | Binder  |      50 |       19.99 | 999.50   |
|  2 | 2/9/21      | Central  | Jardine  | Pencil  |      36 |        4.99 | 179.64   |
|  3 | 2/26/21     | Central  | Gill     | Pen     |      27 |       19.99 | 539.73   |
|  4 | 3/15/21     | West     | Sorvino  | Pencil  |      56 |        2.99 | 167.44   |
|  5 | 4/1/21      | East     | Jones    | Binder  |      60 |        4.99 | 299.40   |
|  6 | 4/18/21     | Central  | Andrews  | Pencil  |      75 |        1.99 | 149.25   |
|  7 | 5/5/21      | Central  | Jardine  | Pencil  |      90 |        4.99 | 449.10   |
|  8 | 5/22/21     | West     | Thompson | Pencil  |      32 |        1.99 | 63.68    |
|  9 | 6/8/21      | East     | Jones    | Binder  |      60 |        8.99 | 539.40   |
| 10 | 6/25/21     | Central  | Morgan   | Pencil  |      90 |        4.99 | 449.10   |
| 11 | 7/12/21     | East     | Howard   | Binder  |      29 |        1.99 | 57.71    |
| 12 | 7/29/21     | East     | Parent   | Binder  |      81 |       19.99 | 1,619.19 |
| 13 | 8/15/21     | East     | Jones    | Pencil  |      35 |        4.99 | 174.65   |
| 14 | 9/1/21      | Central  | Smith    | Desk    |       2 |      125    | 250.00   |
| 15 | 9/1/21      | Central  | Smith    | Desk    |       2 |      125    | 250.00   |
| 16 | 10/5/21     | Central  | Morgan   | Binder  |      28 |        8.99 | 251.72   |
| 17 | 10/22/21    | East     | Jones    | Pen     |      64 |        8.99 | 575.36   |
| 18 | 11/8/21     | East     | Parent   | Pen     |      15 |       19.99 | 299.85   |
| 19 | 11/25/21    | Central  | Kivell   | Pen Set |      96 |        4.99 | 479.04   |
| 20 | 12/12/21    | Central  | Smith    | Pencil  |      67 |        1.29 | 86.43    |
| 21 | 12/29/21    | East     | Parent   | Pen Set |      74 |       15.99 | 1,183.26 |
| 22 | 12/29/21    | East     | Parent   | Pen Set |      74 |       15.99 | 1,183.26 |
| 23 | 2/1/22      | Central  | Smith    | Binder  |      87 |       15    | 1,305.00 |
| 24 | 2/18/22     | East     | Jones    | Binder  |       4 |        4.99 | 19.96    |
| 25 | 3/7/22      | West     | Sorvino  | Binder  |       7 |       19.99 | 139.93   |
| 26 | 3/24/22     | Central  | Jardine  | Pen Set |      50 |        4.99 | 249.50   |
| 27 | 4/10/22     | Central  | Andrews  | Pencil  |      66 |        1.99 | 131.34   |
| 28 | 4/27/22     | East     | Howard   | Pen     |      96 |        4.99 | 479.04   |
| 29 | 5/14/22     | Central  | Gill     | Pencil  |      53 |        1.29 | 68.37    |
| 30 | 5/31/22     | Central  | Gill     | Binder  |      80 |        8.99 | 719.20   |
| 31 | 6/17/22     | Central  | Kivell   | Desk    |       5 |      125    | 625.00   |
| 32 | 7/4/22      | East     | Jones    | Pen Set |      62 |        4.99 | 309.38   |
| 33 | 7/21/22     | Central  | Morgan   | Pen Set |      55 |       12.49 | 686.95   |
| 34 | 7/21/22     | Central  | Morgan   | Pen Set |      55 |       12.49 | 686.95   |
| 35 | 7/21/22     | Central  | Morgan   | Pen Set |      55 |       12.49 | 686.95   |
| 36 | 9/10/22     | Central  | Gill     | Pencil  |       7 |        1.29 | 9.03     |
| 37 | 9/27/22     | West     | Sorvino  | Pen     |      76 |        1.99 | 151.24   |
| 38 | 10/14/22    | West     | Thompson | Binder  |      57 |       19.99 | 1,139.43 |
| 39 | 10/31/22    | Central  | Andrews  | Pencil  |      14 |        1.29 | 18.06    |
| 40 | 11/17/22    | Central  | Jardine  | Binder  |      11 |        4.99 | 54.89    |
| 41 | 12/4/22     | Central  | Jardine  | Binder  |      94 |       19.99 | 1,879.06 |
| 42 | 12/21/22    | Central  | Andrews  | Binder  |      28 |        4.99 | 139.72   |
+----+-------------+----------+----------+---------+---------+-------------+----------+


These are the top 10 contents of SampleData.csv
+----+-------------+----------+----------+--------+---------+-------------+---------+
|    | OrderDate   | Region   | Rep      | Item   |   Units |   Unit Cost |   Total |
|----+-------------+----------+----------+--------+---------+-------------+---------|
|  0 | 1/6/21      | East     | Jones    | Pencil |      95 |        1.99 |  189.05 |
|  1 | 1/23/21     | Central  | Kivell   | Binder |      50 |       19.99 |  999.5  |
|  2 | 2/9/21      | Central  | Jardine  | Pencil |      36 |        4.99 |  179.64 |
|  3 | 2/26/21     | Central  | Gill     | Pen    |      27 |       19.99 |  539.73 |
|  4 | 3/15/21     | West     | Sorvino  | Pencil |      56 |        2.99 |  167.44 |
|  5 | 4/1/21      | East     | Jones    | Binder |      60 |        4.99 |  299.4  |
|  6 | 4/18/21     | Central  | Andrews  | Pencil |      75 |        1.99 |  149.25 |
|  7 | 5/5/21      | Central  | Jardine  | Pencil |      90 |        4.99 |  449.1  |
|  8 | 5/22/21     | West     | Thompson | Pencil |      32 |        1.99 |   63.68 |
|  9 | 6/8/21      | East     | Jones    | Binder |      60 |        8.99 |  539.4  |
+----+-------------+----------+----------+--------+---------+-------------+---------+


These are the bottom 10 contents of SampleData.csv
+----+-------------+----------+----------+---------+---------+-------------+----------+
|    | OrderDate   | Region   | Rep      | Item    |   Units |   Unit Cost | Total    |
|----+-------------+----------+----------+---------+---------+-------------+----------|
| 33 | 7/21/22     | Central  | Morgan   | Pen Set |      55 |       12.49 | 686.95   |
| 34 | 7/21/22     | Central  | Morgan   | Pen Set |      55 |       12.49 | 686.95   |
| 35 | 7/21/22     | Central  | Morgan   | Pen Set |      55 |       12.49 | 686.95   |
| 36 | 9/10/22     | Central  | Gill     | Pencil  |       7 |        1.29 | 9.03     |
| 37 | 9/27/22     | West     | Sorvino  | Pen     |      76 |        1.99 | 151.24   |
| 38 | 10/14/22    | West     | Thompson | Binder  |      57 |       19.99 | 1,139.43 |
| 39 | 10/31/22    | Central  | Andrews  | Pencil  |      14 |        1.29 | 18.06    |
| 40 | 11/17/22    | Central  | Jardine  | Binder  |      11 |        4.99 | 54.89    |
| 41 | 12/4/22     | Central  | Jardine  | Binder  |      94 |       19.99 | 1,879.06 |
| 42 | 12/21/22    | Central  | Andrews  | Binder  |      28 |        4.99 | 139.72   |
+----+-------------+----------+----------+---------+---------+-------------+----------+


These are the contents of SampleDataNew.csv
+----+-------------+----------+----------+---------+---------+-------------+----------+
|    | OrderDate   | Region   | Rep      | Item    |   Units |   Unit Cost | Total    |
|----+-------------+----------+----------+---------+---------+-------------+----------|
|  0 | 1/6/21      | East     | Jones    | Pencil  |      95 |        1.99 | 189.05   |
|  1 | 1/23/21     | Central  | Kivell   | Binder  |      50 |       19.99 | 999.50   |
|  2 | 2/9/21      | Central  | Jardine  | Pencil  |      36 |        4.99 | 179.64   |
|  3 | 2/26/21     | Central  | Gill     | Pen     |      27 |       19.99 | 539.73   |
|  4 | 3/15/21     | West     | Sorvino  | Pencil  |      56 |        2.99 | 167.44   |
|  5 | 4/1/21      | East     | Jones    | Binder  |      60 |        4.99 | 299.40   |
|  6 | 4/18/21     | Central  | Andrews  | Pencil  |      75 |        1.99 | 149.25   |
|  7 | 5/5/21      | Central  | Jardine  | Pencil  |      90 |        4.99 | 449.10   |
|  8 | 5/22/21     | West     | Thompson | Pencil  |      32 |        1.99 | 63.68    |
|  9 | 6/8/21      | East     | Jones    | Binder  |      60 |        8.99 | 539.40   |
| 10 | 6/25/21     | Central  | Morgan   | Pencil  |      90 |        4.99 | 449.10   |
| 11 | 7/12/21     | East     | Howard   | Binder  |      29 |        1.99 | 57.71    |
| 12 | 7/29/21     | East     | Parent   | Binder  |      81 |       19.99 | 1,619.19 |
| 13 | 8/15/21     | East     | Jones    | Pencil  |      35 |        4.99 | 174.65   |
| 14 | 9/1/21      | Central  | Smith    | Desk    |       2 |      125    | 250.00   |
| 16 | 10/5/21     | Central  | Morgan   | Binder  |      28 |        8.99 | 251.72   |
| 17 | 10/22/21    | East     | Jones    | Pen     |      64 |        8.99 | 575.36   |
| 18 | 11/8/21     | East     | Parent   | Pen     |      15 |       19.99 | 299.85   |
| 19 | 11/25/21    | Central  | Kivell   | Pen Set |      96 |        4.99 | 479.04   |
| 20 | 12/12/21    | Central  | Smith    | Pencil  |      67 |        1.29 | 86.43    |
| 21 | 12/29/21    | East     | Parent   | Pen Set |      74 |       15.99 | 1,183.26 |
| 23 | 2/1/22      | Central  | Smith    | Binder  |      87 |       15    | 1,305.00 |
| 24 | 2/18/22     | East     | Jones    | Binder  |       4 |        4.99 | 19.96    |
| 25 | 3/7/22      | West     | Sorvino  | Binder  |       7 |       19.99 | 139.93   |
| 26 | 3/24/22     | Central  | Jardine  | Pen Set |      50 |        4.99 | 249.50   |
| 27 | 4/10/22     | Central  | Andrews  | Pencil  |      66 |        1.99 | 131.34   |
| 28 | 4/27/22     | East     | Howard   | Pen     |      96 |        4.99 | 479.04   |
| 29 | 5/14/22     | Central  | Gill     | Pencil  |      53 |        1.29 | 68.37    |
| 30 | 5/31/22     | Central  | Gill     | Binder  |      80 |        8.99 | 719.20   |
| 31 | 6/17/22     | Central  | Kivell   | Desk    |       5 |      125    | 625.00   |
| 32 | 7/4/22      | East     | Jones    | Pen Set |      62 |        4.99 | 309.38   |
| 33 | 7/21/22     | Central  | Morgan   | Pen Set |      55 |       12.49 | 686.95   |
| 36 | 9/10/22     | Central  | Gill     | Pencil  |       7 |        1.29 | 9.03     |
| 37 | 9/27/22     | West     | Sorvino  | Pen     |      76 |        1.99 | 151.24   |
| 38 | 10/14/22    | West     | Thompson | Binder  |      57 |       19.99 | 1,139.43 |
| 39 | 10/31/22    | Central  | Andrews  | Pencil  |      14 |        1.29 | 18.06    |
| 40 | 11/17/22    | Central  | Jardine  | Binder  |      11 |        4.99 | 54.89    |
| 41 | 12/4/22     | Central  | Jardine  | Binder  |      94 |       19.99 | 1,879.06 |
| 42 | 12/21/22    | Central  | Andrews  | Binder  |      28 |        4.99 | 139.72   |
+----+-------------+----------+----------+---------+---------+-------------+----------+

In [72]:
#display the 1st and 2nd columns
df = pd.read_csv('SampleDataNew.csv')

print(tabulate(df.iloc[:,0:3], headers='keys', tablefmt='psql', showindex = False))

+--------------+-------------+----------+
|   Unnamed: 0 | OrderDate   | Region   |
|--------------+-------------+----------|
|            0 | 1/6/21      | East     |
|            1 | 1/23/21     | Central  |
|            2 | 2/9/21      | Central  |
|            3 | 2/26/21     | Central  |
|            4 | 3/15/21     | West     |
|            5 | 4/1/21      | East     |
|            6 | 4/18/21     | Central  |
|            7 | 5/5/21      | Central  |
|            8 | 5/22/21     | West     |
|            9 | 6/8/21      | East     |
|           10 | 6/25/21     | Central  |
|           11 | 7/12/21     | East     |
|           12 | 7/29/21     | East     |
|           13 | 8/15/21     | East     |
|           14 | 9/1/21      | Central  |
|           16 | 10/5/21     | Central  |
|           17 | 10/22/21    | East     |
|           18 | 11/8/21     | East     |
|           19 | 11/25/21    | Central  |
|           20 | 12/12/21    | Central  |
|           21 | 12/29/21    | East     |
|           23 | 2/1/22      | Central  |
|           24 | 2/18/22     | East     |
|           25 | 3/7/22      | West     |
|           26 | 3/24/22     | Central  |
|           27 | 4/10/22     | Central  |
|           28 | 4/27/22     | East     |
|           29 | 5/14/22     | Central  |
|           30 | 5/31/22     | Central  |
|           31 | 6/17/22     | Central  |
|           32 | 7/4/22      | East     |
|           33 | 7/21/22     | Central  |
|           36 | 9/10/22     | Central  |
|           37 | 9/27/22     | West     |
|           38 | 10/14/22    | West     |
|           39 | 10/31/22    | Central  |
|           40 | 11/17/22    | Central  |
|           41 | 12/4/22     | Central  |
|           42 | 12/21/22    | Central  |
+--------------+-------------+----------+

In [ ]:
#display the 1st and 2nd columns